<template>
  <el-form
    ref="form"
    :model="query"
    class="ot-form--elem"
    v-bind="attrs"
    v-on="listeners"
  >
    <template v-for="(row, index) in rows">
      <el-row
        :key="index"
        v-bind="rowAttrs"
      >
        <!-- Layout is generated by calculation, 布局信息计算生成 -->
        <el-col
          v-for="filter in row"
          :key="filter.prop"
          v-bind="genColAttrs(filter)"
        >
          <button-group
            v-if="showButtonGroup && filter.type === BUTTON_GROUP_TYPE"
            v-bind="buttonGroupAttrs"
            @on-search="$emit('on-search')"
            @on-reset="$emit('on-reset')"
            @on-collapse="handleSetCollapsed"
          />

          <elem-form-item
            v-else
            :filter="filter"
            :query="query"
          />
        </el-col>
      </el-row>
    </template>
  </el-form>
</template>

<script>
import pick from 'lodash/pick';
import throttle from 'lodash/throttle';
import { searchResetProps, proxyMethods, EL_COL_ATTRS } from '@onemin-table/shared';
import ButtonGroup from './components/button-group/index.vue';
import ElemFormItem from './components/form-item.vue';
import ResizeObserver from 'resize-observer-polyfill';

const ROW_SPAN_COUNT = 24;
const ELEM_FORM_ATTRS = [
  'rules',
  'inline',
  'label-position',
  'label-width',
  'label-suffix',
  'hide-required-asterisk',
  'show-message',
  'inline-message',
  'status-icon',
  'validate-on-rule-change',
  'size',
  'disabled',
];
const BUTTON_GROUP_ATTRS = Object.keys(searchResetProps);

export default {
  name: 'ElemForm',

  inheritAttrs: false,

  components: {
    ElemFormItem,
    ButtonGroup,
  },

  props: {
    /**
     * @language=zh
     * 双向绑定的表单数据
     */
    query: {
      type: Object,
      default() { return {}; },
    },

    /**
     * @language=zh
     * 表单元素schema
     */
    filters: {
      type: Array,
      default() { return []; },
    },

    /**
     * @language=zh
     * <el-row />属性
     */
    rowAttrs: {
      type: Object,
      default() {
        return { gutter: 24 };
      },
    },

    /**
     * @language=zh
     * 根据屏幕宽度(document.body.clientWidth)自动布局
     */
    autoLayout: {
      type: Boolean,
      default: false,
    },

    /**
     * @language=zh
     * 列数计算间断点规则（根据document.body.clientWidth计算）
     */
    spanCalcRules: {
      type: Array,
      default() {
        return [
          [0, 768, 24],
          [768, 992, 12],
          [992, 1440, 8],
          [1440, 2560, 6],
          [2560, 4800, 4],
        ];
      },
    },

    /**
     * @language=zh
     * 是否默认收起
     */
    defaultCollapsed: {
      type: Boolean,
      default: false,
    },

    /**
     * @language=zh
     * 是否展示搜索&重置按钮组
     */
    showButtonGroup: {
      type: Boolean,
      default: false,
    },

    ...searchResetProps,
  },

  data() {
    return {
      collapsed: this.defaultCollapsed,

      GLOBAL_SPAN: 8,
      resizeObserver: null,

      BUTTON_GROUP_TYPE: '@onemin-table/button_group',
    };
  },

  computed: {
    // filter with span value in autoLayout mode, 自动布局模式下filters自带span
    filtersWithSpan() {
      const filters = this.autoLayout
        ? this.filters.map((e) => ({ ...e, span: this.GLOBAL_SPAN }))
        : this.filters;

      return filters.filter((e) => e.visible !== false);
    },

    rows() {
      const result = [];

      let tmp = [];
      this.filtersWithSpan.forEach((filter) => {
        const sum = tmp.reduce((a, c) => a + (c.span || 0), 0);
        // fill and change row, 行满推入result
        if (sum >= ROW_SPAN_COUNT) {
          result.push(tmp);
          tmp = [];
        }
        // default input, 默认输入框
        const item = filter;
        if (!item.type && !item.render) item.type = 'input';
        tmp.push(item);
      });
      // push last
      if (tmp.length) result.push(tmp);

      if (this.showButtonGroup) {
        const last = result[result.length - 1];
        // last row max column count, 最后一行最大列数
        const lastMaxCount = ROW_SPAN_COUNT / this.GLOBAL_SPAN;
        const lastCount = last.length;
        // button group column, 搜索&重置按钮组所在列
        const buttonGroupCol = {
          type: this.BUTTON_GROUP_TYPE,
          span: this.GLOBAL_SPAN,
          push: ROW_SPAN_COUNT - this.GLOBAL_SPAN,
        };
        if (lastCount === lastMaxCount) {
          result.push([buttonGroupCol]);
        } else {
          last.push({
            ...buttonGroupCol,
            push: ROW_SPAN_COUNT - ((lastCount + 1) * this.GLOBAL_SPAN),
          });
        }
      }

      return result;
    },

    // form attributes, 表单属性
    attrs() {
      return pick(this.$attrs, ELEM_FORM_ATTRS);
    },

    // form listeners, 表单事件
    listeners() {
      return pick(this.$listeners, ['validate']);
    },

    // layout meta data corrent, 布局信息无误
    calculateable() {
      return Array.isArray(this.spanCalcRules)
        && this.spanCalcRules.every((e) => Array.isArray(e) && e.length === 3);
    },

    // search&reset button group attrs, 搜索重置按钮组属性
    buttonGroupAttrs() {
      const result = pick(this, BUTTON_GROUP_ATTRS);
      // hide collapse when only one row, 只有一行时隐藏收起-展开按钮
      const spanSum = this.filtersWithSpan.reduce((a, c) => a + (c.span || 0), 0);
      if (spanSum < ROW_SPAN_COUNT) {
        result.buttonLayout = result.buttonLayout.filter((e) => e !== 'collapse');
      }

      return result;
    },
  },

  watch: {
    filters() {
      this.$refs?.form?.clearValidate();
    },
  },

  created() {
    this.handleSetCollapsed = (val) => {
      this.collapsed = val;
      this.$emit('on-collapse', val);
    };
  },

  mounted() {
    // Proxy Form Methods, 代理表单方法
    proxyMethods(this, 'form', ['validate', 'validateField', 'resetFields', 'clearValidate']);

    if (this.autoLayout) {
      /**
       * span in auto layout mode
       * 自动布局模式下的span
       */
      const genGloablSpan = throttle(() => {
        if (!this.calculateable) return;

        const width = document.body.clientWidth;
        this.spanCalcRules.forEach(([start, end, span]) => {
          if (width > start && width <= end) {
            this.GLOBAL_SPAN = span;
          }
        });
      }, 200);

      genGloablSpan();
      // detect size change, 观察元素大小改变
      this.resizeObserver = new ResizeObserver(() => {
        window.requestAnimationFrame(genGloablSpan);
      });
      this.resizeObserver.observe(document.body);
    }
  },

  beforeDestroy() {
    if (this.autoLayout && this.resizeObserver) {
      this.resizeObserver.unobserve(document.body);
    }
  },

  methods: {
    // <el-col> attrs, <el-col>属性
    genColAttrs(filter) {
      return pick(filter, EL_COL_ATTRS);
    },
  },
};
</script>

<style>
.ot-form--elem .el-form-item__label {
  padding-right: 16px;
  color: #343A40;
}

.ot-form__button-group {
  white-space: nowrap;
  text-align: right;
}

.ot-form--elem .el-cascader__tags {
  flex-wrap: nowrap;
  overflow: hidden;
}

.ot-form--elem .el-select__tags {
  flex-wrap: nowrap;
  overflow: hidden;
}
</style>
