<template>
  <el-form
    ref="form"
    :model="query"
    v-bind="$attrs"
    v-on="$listeners"
    class="ot-form--elem"
  >
    <template v-for="(row, index) in rowList">
      <!-- Row, 行 -->
      <el-row
        :key="index"
        v-bind="rowAttrs"
      >
        <!-- Layout is generated by calculation, 布局信息计算生成 -->
        <el-col
          v-for="filter in row"
          :key="filter.prop"
          :span="filter.span"
          :offset="filter.offset"
        >
          <el-form-item
            :label="filter.visible !== false ? filter.label : ''"
            :prop="filter.prop"
            v-bind="filter.itemAttrs"
          >
            <!-- If hidden, 是否隐藏 -->
            <template v-if="filter.visible !== false">

              <!-- Select(single and multiple), 选择器(单选与多选) -->
              <el-select
                v-if="filter.type === 'select' || filter.type === 'single-select'"
                v-model="query[filter.prop]"
                :multiple="filter.type !== 'single-select'"
                :popper-append-to-body="genDefaultProp(filter, 'popperAppendToBody')"
                v-bind="genSelectDefaultAttrs(filter)"
                v-on="filter.listeners"
                @change="handleChange(filter)"
              >
                <el-option
                  v-for="(item, i) in (filter.options || [])"
                  :key="i"
                  :label="item.label"
                  :value="item.value"
                  :disabled="item.disabled"
                />
              </el-select>

              <!-- Cascader(single and multiple), 级联选择器(单选与多选) -->
              <el-cascader
                v-else-if="filter.type === 'cascader' || filter.type === 'single-cascader'"
                v-model="query[filter.prop]"
                :options="filter.options"
                :props="genCascaderProps(filter)"
                v-bind="genSelectDefaultAttrs(filter)"
                v-on="filter.listeners"
                @change="handleChange(filter)"
              />

              <!-- Date Picker, 日期选择器 -->
              <el-date-picker
                v-else-if="DATE_TYPES.includes(filter.type)"
                v-model="query[filter.prop]"
                :type="filter.type"
                v-bind="genPickerDefaultAttrs(filter, '日期')"
                v-on="filter.listeners"
                @change="handleChange(filter)"
              />

              <!-- Time Picker, 时间选择器 -->
              <el-time-picker
                v-else-if="TIME_TYPES.includes(filter.type)"
                v-model="query[filter.prop]"
                :is-range="filter.type === 'timerange'"
                v-bind="genPickerDefaultAttrs(filter, '时间')"
                v-on="filter.listeners"
                @change="handleChange(filter)"
              />

              <!-- Checkbox Group, 多选框 -->
              <el-checkbox-group
                v-else-if="filter.type === 'checkbox' || filter.type === 'checkbox-button'"
                v-model="query[filter.prop]"
                :data-prop="filter.prop"
                v-bind="filter.attrs"
                v-on="filter.listeners"
                @change="handleChange(filter)"
              >
                <component
                  :is="`el-${filter.type}`"
                  v-for="(item, i) in (filter.options || [])"
                  :key="i"
                  v-bind="genSelectBoxAttrs(item)"
                >{{ item.label }}</component>
              </el-checkbox-group>

              <!-- Radio Group, 单选框 -->
              <el-radio-group
                v-else-if="filter.type === 'radio' || filter.type === 'radio-button'"
                v-model="query[filter.prop]"
                :data-prop="filter.prop"
                v-bind="filter.attrs"
                v-on="filter.listeners"
                @change="handleChange(filter)"
              >
                <component
                  :is="`el-${filter.type}`"
                  v-for="(item, i) in (filter.options || [])"
                  :key="i"
                  v-bind="genSelectBoxAttrs(item)"
                >{{ item.label }}</component>
              </el-radio-group>

              <!-- Plain Text, 纯文本 -->
              <span
                v-else-if="filter.type === 'text'"
                :data-prop="filter.prop"
              >{{ query[filter.prop] || '' }}</span>

              <!-- Search & Reset Button Group, 搜索重置按钮组 -->
              <div
                v-else-if="filter.type === 'button-group' && showButton"
                class="ot-form__button-group"
              >
                <template
                  v-for="button in buttonGroupList"
                >
                  <component
                    :key="button"
                    :is="button"
                    v-bind="genButtonGroupProps(button)"
                    @on-search="$emit('on-search')"
                    @on-reset="$emit('on-reset')"
                    @on-collapse="handleSetCollapsed"
                  />
                </template>
              </div>

              <!-- InputNumber, 计数器 -->
              <el-input-number
                v-else-if="filter.type === 'input-number'"
                v-model="query[filter.prop]"
                :data-prop="filter.prop"
                :controls-position="genDefaultProp(filter, 'controlsPosition', 'right')"
                :clearable="genDefaultProp(filter, 'clearable')"
                :placeholder="genDefaultProp(filter, 'placeholder', '请输入')"
                v-bind="filter.attrs"
                v-on="filter.listeners"
                @input="handleChange(filter)"
              />

              <!-- Custom render component, 自定义渲染组件 -->
              <custom-render
                v-else-if="typeof filter.render === 'function'"
                :render="filter.render"
              />

              <!-- Default Input, 默认输入框 -->
              <el-input
                v-else-if="filter.type !== 'button-group'"
                v-model="query[filter.prop]"
                :data-prop="filter.prop"
                :clearable="genDefaultProp(filter, 'clearable')"
                :placeholder="genDefaultProp(filter, 'placeholder', '请输入')"
                v-bind="filter.attrs"
                v-on="filter.listeners"
                @input="handleChange(filter)"
              />
            </template>
          </el-form-item>
        </el-col>
      </el-row>
    </template>
  </el-form>
</template>

<script>
import debounce from 'lodash/debounce';
import {
  Form, FormItem, Select, Option, Button, Row, Col, DatePicker, Cascader,
  CheckboxGroup, Checkbox, InputNumber, TimePicker,
} from 'element-ui';
import search from './components/button-group/search.vue';
import reset from './components/button-group/reset.vue';
import collapse from './components/button-group/collapse.vue';
import CustomRender from './components/custom-render';

const DATE_RANGE_TYPES = [
  'dates',
  'datetimerange',
  'daterange',
  'monthrange',
];

const DATE_TYPES = [
  'year',
  'month',
  'date',
  'week',
  'datetime',
  ...DATE_RANGE_TYPES,
];

const TIME_TYPES = ['time', 'timerange'];

const RANGE_TYPES = [
  ...DATE_RANGE_TYPES,
  'timerange',
];

const ROW_SPAN_COUNT = 24;

export default {
  name: 'ElemForm',

  components: {
    ElForm: Form,
    ElFormItem: FormItem,
    ElSelect: Select,
    ElOption: Option,
    ElButton: Button,
    ElRow: Row,
    ElCol: Col,
    ElDatePicker: DatePicker,
    ElCascader: Cascader,
    ElCheckboxGroup: CheckboxGroup,
    ElCheckbox: Checkbox,
    ElInputNumber: InputNumber,
    ElTimePicker: TimePicker,

    search,
    reset,
    collapse,
    CustomRender,
  },

  props: {
    /**
     * @language=zh
     * 双向绑定的表单数据
     */
    query: {
      type: Object,
      default() { return {}; },
    },

    /**
     * @language=zh
     * 表单元素schema
     */
    filters: {
      type: Array,
      default() { return []; },
    },

    /**
     * @language=zh
     * <el-row />属性
     */
    rowAttrs: {
      type: Object,
      default() {
        return { gutter: 24 };
      },
    },

    /**
     * @language=zh
     * 搜索&重置按钮组是否加载中
     */
    loading: {
      type: Boolean,
      default: false,
    },

    /**
     * @language=zh
     * 是否展示搜索&重置按钮组
     */
    showButton: {
      type: Boolean,
      default: false,
    },

    /**
     * @language=zh
     * 搜索&重置按钮组布局
     */
    buttonLayout: {
      type: String,
      default: 'reset, search, collapse',
    },

    /**
     * @language=zh
     * 搜索按钮文本
     */
    searchButtonText: {
      type: String,
      default: '查 询',
    },

    /**
     * @language=zh
     * 重置按钮文本
     */
    resetButtonText: {
      type: String,
      default: '重 置',
    },

    /**
     * @language=zh
     * 收起按钮文本
     */
    collapseButtonText: {
      type: String,
      default: '收起',
    },

    /**
     * @language=zh
     * 展开按钮文本
     */
    expandButtonText: {
      type: String,
      default: '展开',
    },

    /**
     * @language=zh
     * 是否默认收起
     */
    defaultCollapsed: {
      type: Boolean,
      default: false,
    },

    /**
     * @language=zh
     * 列数计算间断点规则（根据document.body.clientWidth计算）
     */
    spanCalcRules: {
      type: Array,
      default() {
        return [
          [0, 768, 24],
          [768, 992, 12],
          [992, 1440, 8],
          [1440, 2560, 6],
          [2560, 4800, 4],
        ];
      },
    },

    /**
     * @language=zh
     * 按钮组的FormItem属性
     */
    buttonGroupItemAttrs: {
      type: Object,
      default() {
        return {
          labelWidth: '0px',
        };
      },
    },

    /**
     * @language=zh
     * 区间选择器占两倍栅格
     */
    rangeDouble: {
      type: Boolean,
      default: false,
    },
  },

  data() {
    return {
      collapsed: this.defaultCollapsed,

      DATE_TYPES,
      TIME_TYPES,
      resizeObserver: null,
      span: 8,
    };
  },

  computed: {
    FILTERS() {
      return this.filters.filter((e) => e.visible !== false).map((filter) => {
        const isRange = RANGE_TYPES.includes(filter.type) && this.rangeDouble;
        return {
          ...filter,
          // 日期区间选择器两倍长度
          span: isRange ? (this.span * 2) : this.span,
        };
      });
    },

    rowList() {
      let result = [];
      let filters = this.FILTERS;

      if (this.collapsed) {
        const items = [];
        for (const filter of this.FILTERS) {
          const sum = items.map((e) => e.span).reduce((a, c) => a + c, 0);
          if (sum + this.span === ROW_SPAN_COUNT) {
            filters = items;
            break;
          }
          items.push(filter);
        }
      }

      let tmp = [];
      filters.forEach((filter) => {
        const sum = tmp.map((e) => e.span).reduce((a, c) => a + c, 0);
        // 行满推入result
        if (sum >= ROW_SPAN_COUNT) {
          result.push(tmp);
          tmp = [];
        }
        tmp.push(filter);
      });
      // push last
      if (tmp.length) result.push(tmp);

      result = this.appendButtonGroup(result);

      return result;
    },

    /**
     * 按钮组件名称排列
     */
    buttonGroupList() {
      let d = this.buttonLayout.split(',').map((e) => e.trim());
      // 单行不显示收起-展开
      if (this.rowList.length === 1 && !this.collapsed) {
        d = d.filter((e) => e !== 'collapse');
      }

      return d;
    },
  },

  watch: {
    filters() {
      this.$refs?.form?.clearValidate();
    },

    rowList() {
      this.initResizeObserver();
    },
  },

  mounted() {
    // Proxy Form Methods, 代理表单方法
    const ref = this.$refs?.form;
    if (ref) {
      ['validate', 'validateField', 'resetFields', 'clearValidate'].forEach((method) => {
        if (typeof ref?.[method] === 'function') {
          this[method] = ref[method];
        }
      });
    }

    this.handleSpanCalc(document.body.clientWidth);
  },

  methods: {
    handleSpanCalc(width) {
      if (Array.isArray(this.spanCalcRules)
        && this.spanCalcRules.every((e) => Array.isArray(e) && e.length === 3)
      ) {
        this.spanCalcRules.forEach(([start, end, span]) => {
          if (width > start && width <= end) {
            this.span = span;
          }
        });
      }
    },

    initResizeObserver() {
      if (typeof ResizeObserver === undefined) return;
      if (this.resizeObserver) return;

      const handler = debounce(() => {
        this.handleSpanCalc(document.body.clientWidth);
      }, 100);

      this.resizeObserver = new ResizeObserver(handler);
      if (this.$el) this.resizeObserver.observe(this.$el);
    },

    appendButtonGroup(result) {
      // 最后一行
      const last = result[result.length - 1];
      const sum = last.map((e) => e.span).reduce((a, c) => a + c, 0);

      // 按钮组
      const buttonGroup = {
        label: '',
        prop: 'buttonGroup',
        type: 'button-group',
        span: this.span,
        itemAttrs: this.buttonGroupItemAttrs,
      };

      const tmp = [];
      const columnCount = ROW_SPAN_COUNT / this.span;
      // 剩余列数
      const demainCount = ((ROW_SPAN_COUNT - sum) / this.span) || columnCount;
      // 填充空位
      for (let i = 0; i < demainCount; i += 1) {
        if (i === demainCount - 1) {
          tmp.push(buttonGroup);
        } else {
          tmp.push({
            label: '',
            prop: `placeholder_${i}`,
            visible: false,
            span: this.span,
          });
        }
      }
      if (demainCount === columnCount) {
        result.push(tmp);
      } else {
        result[result.length - 1] = last.concat(tmp);
      }

      return result;
    },

    handleChange(filter) {
      this.$emit('on-change', {
        filter,
        query: this.query,
      });
    },

    genDefaultProp(filter, key, defaultVal = true) {
      return filter[key] === undefined ? defaultVal : filter[key];
    },

    handleSetCollapsed(val) {
      this.collapsed = val;
      this.$emit('on-collapse', val);
    },

    /**
     * cascader props
     * 级联选择器props
     */
    genCascaderProps(filter) {
      return {
        multiple: filter.type === 'cascader',
        checkStrictly: filter.checkStrictly,
        ...filter.props,
      };
    },

    /**
     * search&reset button group props
     * 搜索&重置按钮组props
     */
    genButtonGroupProps(name) {
      switch (name) {
        case 'search':
          return {
            searchButtonText: this.searchButtonText,
            loading: this.loading,
          };
        case 'reset':
          return {
            resetButtonText: this.resetButtonText,
            loading: this.loading,
          };
        case 'collapse':
          return {
            collapseButtonText: this.collapseButtonText,
            expandButtonText: this.expandButtonText,
            collapsed: this.collapsed,
          };
        default:
          return {};
      }
    },

    /**
     * select default attrs
     * 选择器默认属性
     */
    genSelectDefaultAttrs(filter) {
      const def = this.genDefaultProp;
      return {
        clearable: def(filter, 'clearable'),
        filterable: def(filter, 'filterable'),
        placeholder: def(filter, 'placeholder', '请选择'),
        style: 'width: 100%',
        'collapse-tags': def(filter, 'collapseTags'),
        'data-prop': filter.prop,
        ...filter.attrs,
      };
    },

    /**
     * date/time picker default attrs
     * 日期/时间选择器默认属性
     */
    genPickerDefaultAttrs(filter, text) {
      const def = this.genDefaultProp;
      return {
        clearable: def(filter, 'clearable'),
        style: 'width: 100%',
        'range-separator': def(filter, 'rangeSeparator', '~'),
        'start-placeholder': def(filter, 'startPlaceholder', `开始${text}`),
        'end-placeholder': def(filter, 'endPlaceholder', `结束${text}`),
        placeholder: def(filter, 'placeholder', `选择${text}`),
        'data-prop': filter.prop,
        ...filter.attrs,
      };
    },

    /**
     * checkbox/radio attrs
     * 多选/单选框属性
     */
    genSelectBoxAttrs(item) {
      return {
        label: item.value,
        disabled: item.disabled,
        name: item.name,
        border: item.border,
        size: item.size,
      };
    },
  },
};
</script>

<style>
.ot-form--elem .el-form-item__label {
  padding-right: 16px;
  color: #343A40;
}

.ot-form__button-group {
  white-space: nowrap;
  text-align: right;
}

.ot-form--elem .el-cascader__tags {
  flex-wrap: nowrap;
  overflow: hidden;
}

.ot-form--elem .el-select__tags {
  flex-wrap: nowrap;
  overflow: hidden;
}
</style>
